version: '3.4'

services:
  pg_db:
    image: postgres
    container_name: pg_db_container
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
  corepg:
    image: ${DOCKER_REGISTRY-}corepg
    container_name: webapp_container
    build:
      context: .
      dockerfile: corepg/Dockerfile
    depends_on:
      - pg_db
  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "SuperSecret"
    depends_on:
      - pg_db